server:
  port: 8082

spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}

spring:
  application:
    name: order-service

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
