server:
  port: 8082

spring:
  application:
    name: order-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
  kafka:
    consumer:
      properties:
        spring.json.trusted.packages: "*"
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      properties:
        spring.json.trusted.packages: "*"
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:29092}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
  instance:
    prefer-ip-address: true

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: info
    org.gndwrk: debug
    org.springframework.web: info
    org.springframework.security: info

kafka:
  topics:
    order-created: ${KAFKA_TOPIC_ORDER_CREATED:order-created}
